name: example-subject-enterprise
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  demo:
    runs-on: ubuntu-latest
    environment: bridgedai-demo
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: bridgedai-devsecops/subject-action@v1.0.0
        with:
          subject: Dockerfile
          subject-type: file
          mode: mock

